# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
---
# Vault role handlers

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable vault
  become: true
  ansible.builtin.systemd_service:
    name: "{{ vault_service_name }}"
    enabled: true
    masked: false

- name: Restart vault
  become: true
  ansible.builtin.systemd_service:
    name: "{{ vault_service_name }}"
    state: restarted
