# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
---
galaxy_info:
  role_name: nomad
  author: nomad-infra
  description: Install and configure a Nomad agent (server or client).
  min_ansible_version: "2.11"

dependencies: []
