# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
---
# Common role default variables

common_apt_packages:
  - jq
  - net-tools
  - ntp
  - unzip
  - curl
  - wget

common_hostname: ""


