# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
---
# Copy file from local to remote

- name: Check if destination directory exists
  ansible.builtin.stat:
    path: "{{ item.dst | dirname }}"
  register: helper_dir_stat

- name: Ensure destination directory exists
  become: true
  ansible.builtin.file:
    path: "{{ item.dst | dirname }}"
    state: directory
    owner: "{{ item['owner'] | default('root') }}"
    group: "{{ item['group'] | default('root') }}"
    mode: "{{ item['dir_mode'] | default('0755') }}"
  when: not helper_dir_stat.stat.exists

- name: Copy file from local
  become: true
  ansible.builtin.copy:
    src: "{{ item['src'] }}"
    dest: "{{ item['dst'] }}"
    owner: "{{ item['owner'] | default('root') }}"
    group: "{{ item['group'] | default('root') }}"
    mode: "{{ item['mode'] | default('0644') }}"
  notify: "{{ item['notify'] | default(omit) }}"


